CREATE TABLE files (
	ID bigint auto_increment NOT NULL,
	NAME VARCHAR(500),
	PATH VARCHAR(500),
	SIZE INTEGER,
	DATE_CREATED DATE,
	SAVED BOOLEAN,
	STATUS VARCHAR(30),
	DISCARDED BOOLEAN,
	DATE_DOWNLOADED VARCHAR(100),
	CONSTRAINT FILES_PK PRIMARY KEY (ID)
);
